server:
  port: 7001
eureka:
  instance:
    hostname: localhost  #localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-7002.com:7002/eureka/
